### ISSUE TITLE
Not calling ICEES DILI Endpoint

### ISSUE THREAD

**Issue by cbizon** [ranking-agent/strider#184]
There is a second ICEES endpoint for making use of DILI data.  It's registered in smartapi

1. We should include it
2. It needs a special secret API key in order to work - we can get it from Kara and it has to be held secretly

**Comment by mmersmann** [comment]
If KP registry is refreshed, DILI instance should be pulled in.

API key will no longer be used.

**Comment by cbizon** [comment]
https://github.com/NCATSTranslator/minihackathons/issues/66

The API key requirement has been removed.   I think that we should be getting info from DILI now, but this query returns no results
```
{
  "edges": {
    "e0": {
      "object": "n1",
      "predicates": [
        "biolink:correlated_with"
      ],
      "subject": "n0"
    }
  },
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0005359"
      ],
      "is_set": false,
      "name": "drug-induced liver injury"
    },
    "n1": {
      "categories": [
        "biolink:DiseaseOrPhenotypicFeature"
      ],
      "is_set": false,
      "name": "Disease Or Phenotypic Feature"
    }
  }
}
```

Checked the KP registry and ICEES Dili is not in there.

Relevant for December Demo Workflow B

**Comment by mmersmann** [comment]
@cbizon Because you and I are out next week, I've added this to the ICEES+ KP team meeting agenda for 7/12. Hoping that @karafecho with @patrickkwang and @xu-hao can resolve.

**Comment by cbizon** [comment]
It's because DILI is not in the kp-registry due to a meta_knowledge_graph parsing error.

**Comment by xu-hao** [comment]
The errors are in the config files. And the categories should be "biolink:PascalCase".  I updated the config files and redeployed the DILI instance. I have handed it over to Patrick for testing.

**Comment by xu-hao** [comment]
I also created a github action validator on the icees-api-config repository.

**Comment by patrickkwang** [comment]
Thanks @xu-hao! The ICEES DILI instance is properly registered now. The above query does not complete due to apparently an unexpected output from another KP. I have added some more sanitizing in https://github.com/ranking-agent/strider/pull/224. With that, this all works as planned.

**Comment by karafecho** [comment]
@cbizon : Please confirm that this issue can be closed.

**Comment by karafecho** [comment]
Closing as issue has been addressed.

**Comment by cbizon** [comment]
Hang on, I was just running this query

ICEES DILI seems properly registered, but we're still not returning results to the query

**Comment by cbizon** [comment]
OK, with latest strider push, this is working we are now contacting dili.
